### ISSUE TITLE
IgnoreAllExcept()?

### ISSUE THREAD

**Issue by Ciberusps** [kfinley/TypeMerger#2]
What about IngnoreAllExcept()?

```C#
var result = TypeMerger
                  .IgnoreAllExcept(() => obj2.AnotherProperty)
                  .Merge(obj1, obj2);
```

Result - all properties from obj1 & only obj2.AnotherProperty from obj2.

Do u accept pull requests for this package?

Thank you for the package. Thats something i rly missed in C#

**Comment by kfinley** [comment]
I think that would be a great addition.

And yes I'm happy to accept PRs on this project! I don't have any guidelines up but I'll add that to my list of things to add. All I'll say is just make sure you follow the code formatting that the rest of the code uses as well as add tests for any changes.

**Comment by kfinley** [comment]
There's been no movement on this so it's moving to the ice box.
