### ISSUE TITLE
NetStandard compatible version

### ISSUE THREAD

**Issue by tb-mtg** [kfinley/TypeMerger#4]
Can you make this package's project compatible with netstandard2.0 or even better netstandard2.1?

**Comment by kfinley** [comment]
I haven't been using this lately but just checked and looks like yes I can now move this to netstandard2.1. Which is great!!

netstandard2.0 did not have the required reflection emit classes which is why it targeted netcoreapp instead.

I'll try to get this updated and published this week.

**Comment by kfinley** [comment]
Done!
