### ISSUE TITLE
Ignoring base properties does not work?

### ISSUE THREAD

**Issue by prince272** [kfinley/TypeMerger#6]
Example:

class BaseClass {
public string Name  {get; set;}
}

class DeveriedClass : BaseClass {
}

var deveriedObject = new DeveriedClass { Name = "Prince Owusu"};

var result = TypeMerger.Ignore(() => deveriedObject .Name )
                       .Merge(deveriedObject , new {});

Solution: consider replacing 
![sssdsd](https://user-images.githubusercontent.com/32231909/111316767-718acd80-865b-11eb-98cd-fb9a79272afd.PNG)

**Comment by kfinley** [comment]
Good catch. I've never run into this issue. Feel free to add a PR with the fix if you'd like.

I don't use this utility for anything anymore but I can make the change at some point.

**Comment by prince272** [comment]
I use the utility for merging data alot instead of building a whole duplicate of a model in come causes where model are not needed. Take a look at this code:

       [HttpGet("")]
        public async Task<IActionResult> Populate(int? limit, [FromQuery] CourseFilter filter)
        {
            var result = await courseService.PopulateAsync(limit, filter);

            if (!result.Success) return StatusCode(result.Code, result);

            var courseList = (Page<Course>)result.Data;

            result.Data = TypeMerger.Ignore(() => courseList.Items).Merge(new
            {
                Items = courseList.Items.Select(course => TypeMerger.Merge(new
                { ImageUrl = assetService.GetPublicUrl(course.Image) }, course))
            }, courseList);

            return StatusCode(result.Code, result);
        }

You'll notice that TypeMerger was used to merge image url  into the data and return result.

**Comment by kfinley** [comment]
This is exactly what I used this for as well. I'm glad to hear you get use out of it. 

I'll push out an update with the fix today or tomorrow. Thanks again for reporting the issue.
